name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: npm run lint2
    - name: Label Failure if fails lint
      if: ${{ failure() }}
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.addLabels({
            issue_number: github.event.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['lintfailure']
          })
